---
# check and copy outputs.conf to forward data to splunk

- name: check if /opt/splunkforwarder/etc/system/local dir exist
  stat:
    path: "/opt/splunkforwarder/etc/system/local"
  register: dep_dir_path

- name: report if /opt/splunkforwarder/etc/system/local
  debug:
    msg: WARNING - /opt/splunkforwarder/etc/system/local not exist - check your splunk_uf installation!
  when: dep_dir_path.stat.exists == false

- name: copy outputs.conf to forward data to splunk server
  template:
    src: outputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
  when: dep_dir_path.stat.exists